config/routes.rb
Rails.application.routes.draw do

  resources :ability_matrices

  resources :left_panels

  resources :manpower_plannings

  resources :documents

  resources :file_storages

  resources :approvers

  resources :approvals

  resources :generics
  get "/fillForm/:step_id" => "generics#new", :as => :new_generic_form

  resources :tasks

  resources :notifications

  resources :step_instances

  resources :process_instances

  resources :bands

  resources :groups

  resources :departments

  resources :roles

  resources :employees

  resources :process_masters

  resources :master_steps

  resources :welcomes

  devise_for :users

  match '/delete_notification/:id' => 'notifications#delete_notification', :as => :delete_notification, :via => [:get, :post]
  
  match '/approve_step/:stepId' => 'generics#approve_step', :as => :approve_step, :via => [:get, :post]
  
  match '/approve' => 'approvers#change_state', :as => :change_approver_state, :via => [:get, :post]

  root :to => 'welcomes#index'
  mount RailsAdmin::Engine => '/power_admin', as: 'rails_admin'

end

app/models/approval.rb
class Approval
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :description, type: String
  field :link, type: String
  field :reminder, type: String
  field :repeat_reminder, type: String
  field :escalation, type: String
  field :repeat_escalation, type: String
  
  field :state, type: String, :default => "Pending"
  field :erased, type: Boolean, :default => false

  belongs_to :step_instance
  has_many :approvers, dependent: :destroy


  after_create :complete_obj
  # after_save :check_completion


  def complete_obj
    self.title = "Approval Request"
    self.description = "Please click on the link to perform your task."
    self.link = ""

    self.reminder = self.step_instance['action_obj']['reminder']
    self.repeat_reminder = self.step_instance['action_obj']['repeat_reminder']
    self.escalation = self.step_instance['action_obj']['escalation']
    self.repeat_escalation = self.step_instance['action_obj']['repeat_escalation']
    self.save!

  end

  def send_tasks
    urlHelpers = Rails.application.routes.url_helpers
    task = {title: self.title, description: self.description, link: urlHelpers.approve_step_path(self.step_instance._id)}  
    self.approvers.each do |approver|
      User.find(approver.user_id).send_task(task)
    end
  end

  def check_completion
    check_flag = true
    reject_flag = false
    self.approvers.each do |approver|
      if approver.state != 'Accepted' && approver.state != 'Rejected'
        check_flag = false
      else
        if  approver.state == 'Rejected'
          reject_flag = true
        end
      end
    end
    puts '/********************* check_completion *********************/'
    puts check_flag
    puts '/********************* check_completion *********************/'
    if check_flag
      if reject_flag
        self.terminate_approval
      else
        self.end_approval  
      end
    end
    
  end

  def end_approval
    self.state = 'Completed'
    self.save!
    self.step_instance.end_processing_step    
  end

  def terminate_approval
    self.state = 'Terminated'
    self.save!
    self.step_instance.terminate_processing_step    
    # self.step_instance.process_instance.terminate_processing    
  end

end

app/controllers/approvals_controller.rb
class ApprovalsController < InheritedResources::Base
	
  private

    def approval_params
      params.require(:approval).permit()
    end
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/views/approvals/_form.html.erb
<%= form_for(@approval) do |f| %>
  <% if @approval.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@approval.errors.count, "error") %> prohibited this approval from being saved:</h2>

      <ul>
      <% @approval.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/approvals/edit.html.erb
<h1>Editing Approval</h1>

<%= render 'form' %>

<%= link_to 'Show', @approval %> |
<%= link_to 'Back', approvals_path %>

app/views/approvals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Approvals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @approvals.each do |approval| %>
      <tr>
        <td><%= link_to 'Show', approval %></td>
        <td><%= link_to 'Edit', edit_approval_path(approval) %></td>
        <td><%= link_to 'Destroy', approval, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Approval', new_approval_path %>

app/views/approvals/new.html.erb
<h1>New Approval</h1>

<%= render 'form' %>

<%= link_to 'Back', approvals_path %>

app/views/approvals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_approval_path(@approval) %> |
<%= link_to 'Back', approvals_path %>