config/routes.rb
Rails.application.routes.draw do

  resources :ability_matrices

  resources :left_panels

  resources :manpower_plannings

  resources :documents

  resources :file_storages

  resources :approvers

  resources :approvals

  resources :generics
  get "/fillForm/:step_id" => "generics#new", :as => :new_generic_form

  resources :tasks

  resources :notifications

  resources :step_instances

  resources :process_instances

  resources :bands

  resources :groups

  resources :departments

  resources :roles

  resources :employees

  resources :process_masters

  resources :master_steps

  resources :welcomes

  devise_for :users

  match '/delete_notification/:id' => 'notifications#delete_notification', :as => :delete_notification, :via => [:get, :post]
  
  match '/approve_step/:stepId' => 'generics#approve_step', :as => :approve_step, :via => [:get, :post]
  
  match '/approve' => 'approvers#change_state', :as => :change_approver_state, :via => [:get, :post]

  root :to => 'welcomes#index'
  mount RailsAdmin::Engine => '/power_admin', as: 'rails_admin'

end

app/models/manpower_planning.rb
class ManpowerPlanning
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code, type: String
  field :name, type: String
  field :description, type: String

  field :role, type: String
  field :department, type: String
  field :band, type: String
  field :location, type: String
  field :source, type: String
  field :nature, type: String
  field :vacancy, type: Integer
  field :start_date, type: Date
  field :end_date, type: Date

  # belongs_to :document
  
end

app/controllers/manpower_plannings_controller.rb
class ManpowerPlanningsController < InheritedResources::Base

  private

    def manpower_planning_params
      params.require(:manpower_planning).permit()
    end
end

app/helpers/manpower_plannings_helper.rb
module ManpowerPlanningsHelper
end

app/views/manpower_plannings/_form.html.erb
<%= form_for(@manpower_planning) do |f| %>
  <% if @manpower_planning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manpower_planning.errors.count, "error") %> prohibited this manpower_planning from being saved:</h2>

      <ul>
      <% @manpower_planning.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manpower_plannings/edit.html.erb
<h1>Editing Manpower Planning</h1>

<%= render 'form' %>

<%= link_to 'Show', @manpower_planning %> |
<%= link_to 'Back', manpower_plannings_path %>

app/views/manpower_plannings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manpower Plannings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manpower_plannings.each do |manpower_planning| %>
      <tr>
        <td><%= link_to 'Show', manpower_planning %></td>
        <td><%= link_to 'Edit', edit_manpower_planning_path(manpower_planning) %></td>
        <td><%= link_to 'Destroy', manpower_planning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manpower planning', new_manpower_planning_path %>

app/views/manpower_plannings/new.html.erb
<h1>New Manpower Planning</h1>

<%= render 'form' %>

<%= link_to 'Back', manpower_plannings_path %>

app/views/manpower_plannings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_manpower_planning_path(@manpower_planning) %> |
<%= link_to 'Back', manpower_plannings_path %>