config/routes.rb
Rails.application.routes.draw do

  resources :ability_matrices

  resources :left_panels

  resources :manpower_plannings

  resources :documents

  resources :file_storages

  resources :approvers

  resources :approvals

  resources :generics
  get "/fillForm/:step_id" => "generics#new", :as => :new_generic_form

  resources :tasks

  resources :notifications

  resources :step_instances

  resources :process_instances

  resources :bands

  resources :groups

  resources :departments

  resources :roles

  resources :employees

  resources :process_masters

  resources :master_steps

  resources :welcomes

  devise_for :users

  match '/delete_notification/:id' => 'notifications#delete_notification', :as => :delete_notification, :via => [:get, :post]
  
  match '/approve_step/:stepId' => 'generics#approve_step', :as => :approve_step, :via => [:get, :post]
  
  match '/approve' => 'approvers#change_state', :as => :change_approver_state, :via => [:get, :post]

  root :to => 'welcomes#index'
  mount RailsAdmin::Engine => '/power_admin', as: 'rails_admin'

end

app/models/document.rb
class Document
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code, type: String
  field :name, type: String
  field :file, type: String
  field :version_controlled, type: String
  field :versions, type: Array

  # has_many :manpower_plannings
  # accepts_nested_attributes_for :manpower_plannings
  # has_many :employees
  # accepts_nested_attributes_for :employees
end

app/controllers/documents_controller.rb
class DocumentsController < InheritedResources::Base

  private

    def document_params
      params.require(:document).permit()
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>