config/routes.rb
Rails.application.routes.draw do

  resources :ability_matrices

  resources :left_panels

  resources :manpower_plannings

  resources :documents

  resources :file_storages

  resources :approvers

  resources :approvals

  resources :generics
  get "/fillForm/:step_id" => "generics#new", :as => :new_generic_form

  resources :tasks

  resources :notifications

  resources :step_instances

  resources :process_instances

  resources :bands

  resources :groups

  resources :departments

  resources :roles

  resources :employees

  resources :process_masters

  resources :master_steps

  resources :welcomes

  devise_for :users

  match '/delete_notification/:id' => 'notifications#delete_notification', :as => :delete_notification, :via => [:get, :post]
  
  match '/approve_step/:stepId' => 'generics#approve_step', :as => :approve_step, :via => [:get, :post]
  
  match '/approve' => 'approvers#change_state', :as => :change_approver_state, :via => [:get, :post]

  root :to => 'welcomes#index'
  mount RailsAdmin::Engine => '/power_admin', as: 'rails_admin'

end

app/models/band.rb
class Band
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_and_belongs_to_many :employees
end

app/controllers/bands_controller.rb
class BandsController < InheritedResources::Base

  private

    def band_params
      params.require(:band).permit()
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>